### ISSUE TITLE
Provide single CLI distribution

### ISSUE THREAD

**Issue by bdemers** [ota4j-team/open-test-reporting#119]
It looks like the current cli jar: 
https://repo1.maven.org/maven2/org/opentest4j/reporting/open-test-reporting-cli/0.1.0-M2/open-test-reporting-cli-0.1.0-M2.jar
Doesn't provide an executable CLI, the user must construct classpath

It would be nice (at least for evaluation purposes), to have a single distribution of the CLI, either a executable uberjar, or GraalVM native image, (or other zip with scripts distribution).

NOTE: If something like this already exists, and I missed it, sorry in advance!

**Comment by marcphilipp** [comment]
Hi Brian, thanks for raising this issue! That's indeed missing. I'll have a look!
