### ISSUE TITLE
Add support for Git metadata

### ISSUE THREAD

**Issue by ericdriggs** [ota4j-team/open-test-reporting#28]
providing SCM context would provide valuable context to determine relevancy of test request
currently this context often only exists in the test orchestration layer, e.g. Jenkins

by including this as a first order part of the test report it allows for test ingestion independent of orchestration implementation

fields:

* org (organization)
* repo (repository)
* branch
* sha

**Comment by marcphilipp** [comment]
@ericdriggs I've just submitted #180. Feedback welcome!
