### ISSUE TITLE
Add a schema for attachments

### ISSUE THREAD

**Issue by leonard84** [ota4j-team/open-test-reporting#3]
## Motivation

I think the use-case to have arbitrary attachments should be universal enough to merit inclusion in OTR directly, instead of every implementer creating a custom solution for this problem.

### Implementation suggestion:

We could either have a generic `attachment` element that has html-attributes like `src=URL`, `type=[image,video,file]`,
or we could have dedicated elements `image[Attachment]`, `video[Attachment]`, ...

The CLI tool should probably support moving local attachments to a new folder structure.

**Comment by marcphilipp** [comment]
I'm in favor of a generic attachment which can either point to an external location via a URL or (for small files) its content can be included directly inside the report in base64-encoded form.

**Comment by marcphilipp** [comment]
WIP PR: https://github.com/junit-team/junit5/pull/3336
