### ISSUE TITLE
CI-Job for tests and publish result

### ISSUE THREAD

**Issue by stbischof** [ota4j-team/open-test-reporting#7]
It would be nice if this project could have aCI-Job that tests and create and publish its own test file. `eat your own dog-food`

**Comment by marcphilipp** [comment]
Very good point! This was addressed in 674b1f44a03de7b502cc95401f185bc2410beff8 and cff46ee545116c8929702d414f2fcc26821ee79e

**Comment by stbischof** [comment]
Thx
