### ISSUE TITLE
Support arbitrary metadata at the test case level

### ISSUE THREAD

**Issue by ericdriggs** [ota4j-team/open-test-reporting#96]
Neither the junit spec nor the current open test reporting spec supports the level of metadata needed for functional traceability.

Ideally annotations from test cases could be populated in the map of metadata to communicate information like this test case covers issue FOO-123 in a ticketing/issue system.

**Comment by marcphilipp** [comment]
You should be able to use the [`data` element](https://github.com/ota4j-team/open-test-reporting/blob/main/schema/src/main/resources/org/opentest4j/reporting/schema/core.xsd#L54) for that which is populated by JUnit's implementation from report entries that can be submitted by JUnit extensions.

**Comment by ericdriggs** [comment]
Thanks for the clarification.
Seems like TestInfo metadata tags would be an even better fit

https://github.com/ota4j-team/open-test-reporting/blob/0315b8f1b42d77205e50043806a3e2543e8ffd5c/schema/src/main/resources/org/opentest4j/reporting/schema/core.xsd#L20
